// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkZk56mRiyXxllJtQ_pDSHSUYJlHmXHH4',
    appId: '1:79100517310:web:2fa18f98c6ad886cfd37ef',
    messagingSenderId: '79100517310',
    projectId: 'news-app-d4d2d',
    authDomain: 'news-app-d4d2d.firebaseapp.com',
    storageBucket: 'news-app-d4d2d.firebasestorage.app',
    measurementId: 'G-SD0PLNP7QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIE6M0pJ27ZaFHGSOvBz0fvA5_8pY52v0',
    appId: '1:79100517310:android:97f4af752c178a79fd37ef',
    messagingSenderId: '79100517310',
    projectId: 'news-app-d4d2d',
    storageBucket: 'news-app-d4d2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-UObNpGbDiARZfCCSDV3JypeC1EdE9G0',
    appId: '1:79100517310:ios:ead34dcfe41aebf2fd37ef',
    messagingSenderId: '79100517310',
    projectId: 'news-app-d4d2d',
    storageBucket: 'news-app-d4d2d.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );
}
